name: bump-version

on:
  workflow_call:
    inputs:
      version:
        required: True
        type: string

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Get current version
        id: current_version
        run: |
          tag=$(git describe --abbrev=0)
          echo "substring=${tag#v}" >> $GITHUB_OUTPUT

      - name: Extract new version
        id: new_version
        uses: bhowell2/github-substring-action@v1.0.0
        with:
          value: ${{ inputs.version }}
          index_of_str: v
          fail_if_not_found: false
          default_return_value: ${{ inputs.version }}
          
      - name: Find and replace the current version
        id: find_replace
        uses: jacobtomlinson/gha-find-replace@2.0.0
        with:
          find: "${{ steps.current_version.outputs.substring }}"
          replace: "${{ steps.new_version.outputs.substring }}"
          include: "{*/{CMakeLists.txt,package.xml,setup.py},docker-compose*.yml}"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4.2.1
        with:
          commit-message: "ci: bump version to ${{ steps.new_version.outputs.substring }} from ${{ steps.current_version.outputs.substring }}"
          branch: bump-version/${{ steps.new_version.outputs.substring }}
          delete-branch: true
          base: ${{ github.event.repository.default_branch }}
          title: "ci: bump version to ${{ steps.new_version.outputs.substring }} from ${{ steps.current_version.outputs.substring }}"
          assignees: kevinanschau
          reviewers: kevinanschau
