name: compose-up

on:
  workflow_call:
    inputs:
      environment:
        required: False
        type: string
        default: staging
      ros-distro:
        required: True
        type: string
    
jobs:
  compose-up:
    runs-on: self-hosted
    environment: ${{ inputs.environment }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.1.0

      - name: Log in to Docker
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: mantistechnologies/${{ github.event.repository.name }}
          flavor: |
            latest=false
            suffix=-${{ inputs.ros-distro }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{raw}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=sha

      - name: Compose Up
        env:
          NAMESPACES: stand1,stand2,stand3,stand4
          LOG_LEVEL: debug
          IMAGE_TAG: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
        run: docker compose up -d
