name: docker-build-and-push

on:
  workflow_call:
    inputs:
      ros-distro:
        required: true
        type: string

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup SSH agent
        if: env.SSH_PRIVATE_KEY
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        # Workaround checking whether the secret is empty.
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: mantistechnologies/${{ github.event.repository.name }}
          flavor: |
            latest=false
            suffix=-${{ inputs.ros-distro }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{raw}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=sha

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3.2.0
        with:
          build-args: ROS_DISTRO=${{ inputs.ros-distro }}
          cache-from: type=registry,ref=mantistechnologies/${{ github.event.repository.name }}:buildcache-${{ inputs.ros-distro }}
          cache-to: type=registry,ref=mantistechnologies/${{ github.event.repository.name }}:buildcache-${{ inputs.ros-distro }},mode=max
          push: true
          ssh: default=${{ env.SSH_AUTH_SOCK }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: runtime
